/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: (typeof import('./../components/Common/CommonFooter.vue'))['default']
    CommonHeader: (typeof import('./../components/Common/CommonHeader.vue'))['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: (typeof import('./../components/Common/Footer.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YoutubePlayer: typeof import('./../components/YoutubePlayer.vue')['default']
  }
}
